name: notti
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  firebase_messaging: ^14.7.19
  flutter:
    sdk: flutter
  overlay_support: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
